### ISSUE TITLE
Masking details

### ISSUE THREAD

**Issue by lirenzhucn** [czbiohub/noise2self#11]
In the paper, for ImageNet, CellNet and HanZi, it seems like you used uniform random replacement instead of local average replacement for masked pixels and you also mentioned "J is chosen randomly for each batch with density 1/25". However, in `mask.py` of this repo, I only seem to see local average replacement and zero replacement, also there seems to be only grid masking instead of random masking. I was wondering if you have tested the effect of random replacement vs. average replacement and grid masking vs. random masking. Thank you.

**Comment by batson** [comment]
Correct. In the manuscript we did use random masking and random replacements as well, but that is not implemented here. We did not see a large difference between the two schemes, anecdotally, but we have not performed a systematic comparison.

**Comment by lirenzhucn** [comment]
> Correct. In the manuscript we did use random masking and random replacements as well, but that is not implemented here. We did not see a large difference between the two schemes, anecdotally, but we have not performed a systematic comparison.

Thanks for the reply. That answers my question.
