### ISSUE TITLE
I cannot replicate the result of Single-Shot Denoising.ipynb

### ISSUE THREAD

**Issue by tunthoi** [czbiohub/noise2self#6]
I got psnr 5.649804873461257
Try with pytorch in windows

**Comment by batson** [comment]
Thanks for raising this issue. The problem appears to be due to downscaling the image twice (once in a conversion to float, then manually by dividing by 256). An attempted fix is in #7 .

**Comment by batson** [comment]
I believe @yinawang28 also encountered this issue.

**Comment by batson** [comment]
Fixed in #7
