### ISSUE TITLE
Local averaging in mask

### ISSUE THREAD

**Issue by the-lay** [czbiohub/noise2self#8]
First of all, very interesting work, thanks!

I've noticed in the supplement of paper that convolution weights for local averaging are `(0 0.25 0; 0.25 0 0.25; 0 0.25 0)` but in the code you use [`(0.5 1.0 0.5; 1.0 0.0 1.0; 0.5 1.0 0.5)`](https://github.com/czbiohub/noise2self/blob/2e351cb69ba9802cfee275be187aeee6bc17fda6/mask.py#L80).

I was wondering, is there a particular reason?
Did you try to experiment with those neighborhood weights?

**Comment by batson** [comment]
There is no particular reason for that change, other than aesthetics (I
like the idea of using all neighboring pixels better). We did the
experiments for the paper with just the four neighbors and didn’t feel like
redoing. I expect perf will be quite similar but we did not test
systematically.

**Comment by the-lay** [comment]
Thanks!
