### ISSUE TITLE
Missing assignment for output?

### ISSUE THREAD

**Issue by asberk** [czbiohub/noise2self#9]
On the line linked below, I noticed that the output is not assigned to a variable. Should it be assigned to `x` or a new variable `c3`? I wonder, because it doesn't look like the operation is inplace, but perhaps I am mistaken.
https://github.com/czbiohub/noise2self/blob/2e351cb69ba9802cfee275be187aeee6bc17fda6/models/babyunet.py#L32

**Comment by batson** [comment]
Great catch. Fixed in b306ca7.
